### PR TITLE
NUnit3 test case id attribute enhancement

### PR DESCRIPTION
**Pull request by Zie62**
[IN:7593]

Test case IDs can now be assigned using attributes on test cases in c#. Test case ID should be able to be parsed as a string or an integer. Failing to have a relevant test case id assigned in either the JSON file or this causes the console runner to crash (Which I believe was the previous behavior). 
Example of new usage:
`
[Test, Property("testcaseid", 298)] 

public void TestAMethod() 

{ 
    Assert.AreEqual(Method(), "Expected Outcome"); 
}
`

### CODE REVIEW

**Comment by simonhbor** [comment]
Everything looks good in the code. I had not appreciated that the JSON file would still be needed. But I see that we still need it for authentication. This makes sense. 
While we are looking at this though, in NUnit 2 we put a configuration section at the top of each test suite - like below. Is that possible in nunit3 or is the JSON 100% required? Let me know and we can work out what to do next (if anything).

`[
    TestFixture,
    SpiraTestConfiguration (
     "http://<server name>/SpiraTest",
     "<username>",
     "<password>",
     <project id>,
     <release id>,
     <test set id>,
     <runner name>
)
    ]`

**Review by simonhbor — APPROVED** [review]
Code looks like it meets the requirements and is nice and straightforward.
See my other comment about a wider question about the JSON file

**Comment by Zie62** [comment]
We could set it up to not need the JSON file at all but it would be considerably more complex than this fix was - I only went as far as test case IDs since that is what the incident was named / about.

**Comment by simonhbor** [comment]
Ok that is good to know. I think the json for configuration has mostly upside so let's leave it as is and then see what users think

**Pull request merged**
